use anyhow::Result;
use bme280::{i2c::BME280, Measurements};
use embedded_svc::mqtt::client::QoS;
use esp_idf_svc::{
    eventloop::EspSystemEventLoop,
    hal::{
        delay::Delay,
        i2c::{I2cConfig, I2cDriver},
        prelude::*,
        temp_sensor::{TempSensorConfig, TempSensorDriver},
    },
    mqtt::client::{EspMqttClient, MqttClientConfiguration},
};
use log::info;
use schili_api::mq_topics::{chip_temperature_topic, hello_topic, sensor_temperature_topic};
use std::{thread::sleep, time::Duration};
use wifi::wifi;

mod wifi;

const UUID: &str = "42"; //get_uuid::uuid();

#[toml_cfg::toml_config]
pub struct Config {
    #[default("localhost")]
    mqtt_host: &'static str,
    #[default("")]
    mqtt_user: &'static str,
    #[default("")]
    mqtt_pass: &'static str,
    #[default("hgf")]
    wifi_ssid: &'static str,
    #[default("")]
    wifi_psk: &'static str,
}

fn main() -> Result<()> {
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();

    let peripherals = Peripherals::take().unwrap();
    let sysloop = EspSystemEventLoop::take()?;

    // The constant `CONFIG` is auto-generated by `toml_config`.
    let app_config = CONFIG;

    // Connect to the Wi-Fi network
    let _wifi = wifi(
        app_config.wifi_ssid,
        app_config.wifi_psk,
        peripherals.modem,
        sysloop,
    )?;

    info!("Our UUID is:");
    info!("{}", UUID);

    let tps_config = TempSensorConfig::default();
    let mut tp_driver = TempSensorDriver::new(&tps_config, peripherals.temp_sensor).unwrap();

    tp_driver.enable().unwrap();

    let pins = peripherals.pins;
    let sda = pins.gpio6;
    let scl = pins.gpio7;
    let i2c = peripherals.i2c0;
    let config = I2cConfig::new().baudrate(100.kHz().into());
    let i2c = I2cDriver::new(i2c, sda, scl, &config)?;

    let mut bme280_sensor = BME280::new_primary(i2c);
    let mut delay = Delay::new(10);

    if let Err(e) = bme280_sensor.init(&mut delay) {
        panic!("bme280 sensor init failed for I2C!: error: {:?}", e);
    }

    // Client configuration:
    let broker_url = if app_config.mqtt_user != "" {
        format!(
            "mqtt://{}:{}@{}",
            app_config.mqtt_user, app_config.mqtt_pass, app_config.mqtt_host
        )
    } else {
        format!("mqtt://{}", app_config.mqtt_host)
    };

    let mqtt_config = MqttClientConfiguration::default();

    // Your Code:

    // 1. Create a client with default configuration and empty handler
    let mut client = EspMqttClient::new_cb(&broker_url, &mqtt_config, move |_message_event| {
        // handler code
    })?;

    // 2. publish an empty hello message
    let payload: &[u8] = &[];
    client.enqueue(&hello_topic(UUID), QoS::AtLeastOnce, true, payload)?;

    loop {
        sleep(Duration::from_secs(1));
        let temp_val = tp_driver.get_celsius().unwrap();
        info!("chip temperature: {}", temp_val);

        // 3. publish CPU temperature
        // client.publish( ... )?;
        client.enqueue(
            &chip_temperature_topic(UUID),
            QoS::AtLeastOnce,
            false,
            &temp_val.to_be_bytes() as &[u8],
        )?;

        match bme280_sensor.measure(&mut delay) {
            Ok(Measurements { temperature, .. }) => {
                info!("sensor temperature: {}", temperature);
                client.enqueue(
                    &sensor_temperature_topic(UUID),
                    QoS::AtLeastOnce,
                    false,
                    &temperature.to_be_bytes() as &[u8],
                )?;
            }
            Err(e) => {
                info!("bme280 measurement error: {:?}", e);
            }
        }
    }
}
