use anyhow::{anyhow, Result};
use bigdecimal::{BigDecimal, FromPrimitive};
use bme280::{i2c::BME280, Measurements};
use chrono::NaiveDateTime;
use ds1307::{DateTimeAccess, Ds1307};
use embedded_svc::{
    http::{client::Client, Headers},
    mqtt::client::MessageId,
};
use esp32c3_sensor_mq::{
    mq135_2::{GasType, Mq135},
};
use esp_idf_svc::{
    eventloop::EspSystemEventLoop,
    hal::{
        adc::{
            attenuation::DB_11,
            oneshot::{
                config::{AdcChannelConfig, Calibration},
                AdcChannelDriver, AdcDriver,
            },
            Resolution, ADC1,
        },
        delay::Delay,
        gpio::{Gpio2, Gpio3, Gpio4},
        i2c::{I2cConfig, I2cDriver, I2cError},
        modem::Modem,
        peripherals::Peripherals,
        temp_sensor::{TempSensor, TempSensorConfig, TempSensorDriver},
        units::Hertz,
    },
    http::{
        client::{Configuration, EspHttpConnection},
        Method,
    },
    io::Read,
    mqtt::client::{EspMqttClient, MqttClientConfiguration, QoS},
    sys::{esp_light_sleep_start, esp_sleep_enable_timer_wakeup, EspError},
    wifi::{BlockingWifi, EspWifi},
};
use log::{error, info};
use schili_api::{
    api::{self, SensorType},
    mq_topics::TOPICS,
};
use std::{thread::sleep, time::Duration};

#[toml_cfg::toml_config]
pub struct Config {
    #[default("localhost")]
    mqtt_host: &'static str,
    #[default("")]
    mqtt_user: &'static str,
    #[default("")]
    mqtt_pass: &'static str,
    #[default("localhost")]
    http_host: &'static str,
    #[default("")]
    wifi_ssid: &'static str,
    #[default("")]
    wifi_psk: &'static str,
    #[default(false)]
    feature_co2_sensor_active: bool,
}

#[derive(Debug)]
struct MeasurementsF32 {
    temperature: f32,
    humidity: f32,
    air_pressure: f32,
    chip_temperature: f32,
    light_intensity: f32,
    battery_voltage: f32,
    measure_time: NaiveDateTime,
}

fn main() -> ! {
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();
    let mut peripherals = Peripherals::take().unwrap();
    loop {
        if let Err(e) = measure_loop(&mut peripherals) {
            error!("Error in measure loop: {e}");
        }
    }
}

fn measure_loop(peripherals: &mut Peripherals) -> Result<()> {
    let sysloop = EspSystemEventLoop::take()?;

    // The constant `CONFIG` is auto-generated by `toml_config`.
    let app_config = CONFIG;

    {   
        let (wifi, connect_errors) =
        esp32c3_sensor_mq::wifi::wifi(app_config.wifi_ssid, app_config.wifi_psk,&mut peripherals.modem , sysloop.clone())?;

        let i2c0 = &mut peripherals.i2c0;
        let sda_gpio6 = &mut peripherals.pins.gpio6;
        let scl_gpio7 = &mut peripherals.pins.gpio7;
        let config = I2cConfig::new().baudrate(Hertz::from(100 * 1000));
        let mut i2c = I2cDriver::new(i2c0, sda_gpio6, scl_gpio7, &config)?;

        let cur_date_time = get_cur_datetime_from_server(&app_config, &mut i2c)?;

        let mut mqtt_client = setup_mqtt_client(&app_config)?;
        for e in connect_errors {
            publish_sensor_error_log_err(&mut mqtt_client, e, cur_date_time);
        }

        stop_mqtt_client_and_wifi(wifi, mqtt_client, sysloop.clone())?;
    }

    const MAX_STORED_MEASUREMENTS: usize = 6;
    let mut stored_measurements: Vec<MeasurementsF32> = Vec::with_capacity(MAX_STORED_MEASUREMENTS);

    loop {
        sleep(std::time::Duration::from_millis(10));

        let temp_sensor = &mut peripherals.temp_sensor;
        let adc1 = &mut peripherals.adc1;
        let i2c0 = &mut peripherals.i2c0;
        let sda_gpio6 = &mut peripherals.pins.gpio6;
        let scl_gpio7 = &mut peripherals.pins.gpio7;

        let gpio2 = &mut peripherals.pins.gpio2;
        let gpio3 = &mut peripherals.pins.gpio3;
        //let gpio4 = &mut peripherals.pins.gpio4;

        let config = I2cConfig::new().baudrate(Hertz::from(100 * 1000));
        let mut i2c = I2cDriver::new(i2c0, sda_gpio6, scl_gpio7, &config)?;

        let mut sleep_dur = std::time::Duration::from_mins(1);
        let sysloop = sysloop.clone();

        match measure_sensor_data(
            temp_sensor,
            &mut i2c,
            adc1,
            gpio2,
            gpio3,
            //gpio4,
        ) {
            Err(e) => {
                let cur_datetime = cur_datetime(&mut i2c)?;
                let (wifi, mut mqtt_client) =
                    get_wifi_and_mqtt_client(&app_config, &mut peripherals.modem, sysloop.clone(), cur_datetime)?;
                publish_sensor_error_log_err(&mut mqtt_client, e, cur_datetime);
                stop_mqtt_client_and_wifi(wifi, mqtt_client, sysloop.clone())?;
            }
            Ok(m) => {
                if m.light_intensity < 100. || m.battery_voltage < 3.0 {
                    sleep_dur = std::time::Duration::from_mins(5);
                    stored_measurements.push(m);
                    if stored_measurements.len() >= MAX_STORED_MEASUREMENTS {
                        let cur_datetime = cur_datetime(&mut i2c)?;
                        let (wifi, mut mqtt_client) = get_wifi_and_mqtt_client(
                            &app_config,
                            &mut peripherals.modem,
                            sysloop.clone(),
                            cur_datetime,
                        )?;
                        publish_measurements(&mut mqtt_client, &mut stored_measurements)?;
                        stored_measurements.clear();
                        stop_mqtt_client_and_wifi(wifi, mqtt_client, sysloop.clone())?;
                    }
                } else {
                    stored_measurements.push(m);
                    let cur_datetime = cur_datetime(&mut i2c)?;
                    let (wifi, mut mqtt_client) = get_wifi_and_mqtt_client(
                        &app_config,
                        &mut peripherals.modem,
                        sysloop.clone(),
                        cur_datetime,
                    )?;
                    publish_measurements(&mut mqtt_client, &mut stored_measurements)?;
                    stored_measurements.clear();
                    stop_mqtt_client_and_wifi(wifi, mqtt_client, sysloop)?;
                }
            }
        }

        // Configure Wakeup Sources
        //SAFETY:
        // wait for 1 second, so mqtt messages and other processes can be finished
        // dropped mqtt client and disconnected and stopped wifi
        // wait 100 millis for wifi to actually stop
        unsafe {
            esp_sleep_enable_timer_wakeup(sleep_dur.as_micros().try_into()?);
            esp_light_sleep_start();
        }
    }
}

fn get_wifi_and_mqtt_client<'m>(
    app_config: &Config,
    modem: &'m mut Modem,
    sysloop: EspSystemEventLoop,
    cur_datetime: NaiveDateTime,
) -> anyhow::Result<(Box<EspWifi<'m>>, EspMqttClient<'static>)> {
    // Connect to the Wi-Fi network
    let (wifi, connect_errors) =
        esp32c3_sensor_mq::wifi::wifi(app_config.wifi_ssid, app_config.wifi_psk, modem, sysloop)?;

    let mut client = setup_mqtt_client(&app_config)?;
    for e in connect_errors {
        publish_sensor_error_log_err(&mut client, e, cur_datetime);
    }
    Ok((wifi, client))
}

fn stop_mqtt_client_and_wifi<'m>(
    mut wifi: Box<EspWifi<'m>>,
    mqtt_client: EspMqttClient<'static>,
    sysloop: EspSystemEventLoop,
) -> anyhow::Result<()> {
    // wait for data to be send
    // the wait time needs to be relatively long
    // 50 ms was not enough, so increased it to half a second
    // otherwise the chip will go to sleep before data could be send
    sleep(std::time::Duration::from_secs(1));

    // deactivate mqtt client and wifi before going into sleep
    let mut wifi = BlockingWifi::wrap(wifi.as_mut(), sysloop)?;

    drop(mqtt_client);
    wifi.disconnect()?;
    wifi.stop()?;

    // wait for wifi to stop
    sleep(std::time::Duration::from_millis(100));

    Ok(())
}

fn get_cur_datetime_from_server<'m, 'i: 'm>(
    app_config: &Config,
    i2c: &'m mut I2cDriver<'i>,
) -> anyhow::Result<NaiveDateTime> {
    let mut ds1307 = Ds1307::new(i2c);
    let http_con = EspHttpConnection::new(&Configuration::default())?;
    let mut http_client = Client::wrap(http_con);

    // get time from server rest api
    let uri = format!("http://{}/datetime/current/local", &app_config.http_host);
    let request = http_client.request(Method::Get, &uri, &[])?;

    // Submit the request and check the status code of the response.
    let mut response = request.submit()?;
    let status = response.status();
    match status {
        200..=299 => {
            let content_len = response.content_len().unwrap_or(0) as usize;
            if content_len <= 256 {
                let mut buf = [0_u8; 256];
                match Read::read(&mut response, &mut buf) {
                    Ok(_size) => {
                        let datetime: NaiveDateTime =
                            serde_json::from_slice(&buf[0..content_len])?;
                        info!("datetime local from server: {datetime}");
                        ds1307.set_datetime(&datetime).map_err(|e| {
                            anyhow!("DS1307 unable to set start datetime. Error: {e:?}")
                        })?;
                        info!("Is ds1307 running: {:?}", ds1307.running());
                        ds1307.set_running()
                            .map_err(|e| anyhow!("Could not start ds1307 clock to running. Error: {e:?}"))?;
                        let datetime = ds1307.datetime()
                            .map_err(|e| anyhow!("Could not get current rtc time from ds1307. Error: {e:?}"))?;
                        Ok(datetime)
                    }
                    Err(e) => Err(anyhow!(
                        "Error occurred reading response buffer. Error: {e}"
                    )),
                }
            } else {
                Err(anyhow!("Could not retrieve current datetime from server.
                                Content length of server response is to longer than 256 bytes. Content length: {content_len}"))
            }
        }
        _ => Err(anyhow!(
            "Could not retrieve current datetime from server.
                            Received status code: {status} {}",
            response.status_message().unwrap_or("")
        )),
    }
}

fn setup_mqtt_client(app_config: &Config) -> Result<EspMqttClient<'static>, EspError> {
    // Client configuration:
    let broker_url = if app_config.mqtt_user != "" {
        format!(
            "mqtt://{}:{}@{}",
            app_config.mqtt_user, app_config.mqtt_pass, app_config.mqtt_host
        )
    } else {
        format!("mqtt://{}", app_config.mqtt_host)
    };

    let mqtt_config = MqttClientConfiguration::default();

    // Your Code:

    // 1. Create a client with default configuration and empty handler
    let client = EspMqttClient::new_cb(&broker_url, &mqtt_config, move |_message_event| {
        // handler code
    });
    client
}

fn cur_datetime(i2c: &mut I2cDriver) -> anyhow::Result<NaiveDateTime> {
    let mut ds1307 = Ds1307::new(i2c);
    ds1307
        .datetime()
        .map_err(|e| anyhow!("Could not read current datetime from ds1307. Error: {e:?}"))
}

fn measure_sensor_data<'m, 'i: 'm>(
    temp_sensor: &mut TempSensor,
    i2c: &'m mut I2cDriver<'i>,
    adc1: &mut ADC1,
    gpio2: &mut Gpio2,
    gpio3: &mut Gpio3,
    //gpio4: &mut Gpio4,
) -> Result<MeasurementsF32> {
    let tps_config = TempSensorConfig::default();
    let mut tp_driver = TempSensorDriver::new(&tps_config, temp_sensor)?;

    tp_driver.enable()?;

    let (mut bme280_sensor, delay) = setup_bme280_temp_hum_airpr_sensor(i2c)?;

    let adc = AdcDriver::new(adc1)?;

    let adc_config = AdcChannelConfig {
        attenuation: DB_11,
        calibration: Calibration::None,
        resolution: Resolution::Resolution12Bit,
    };

    /*
    let mut adc_pin = AdcChannelDriver::new(&adc, gpio4, &adc_config)?;

    let mut co2_sensor = if app_config.feature_co2_sensor_active {
        let co2_adc_val = adc.read(&mut adc_pin)?;
        Some(setup_co2_sensor(co2_adc_val)?)
    } else {
        None
    };
    */

    let (temperature, humidity, air_pressure) = measure_bme280_values(&mut bme280_sensor, delay)?;
    drop(bme280_sensor);

    let chip_temperature = measure_chip_temperature(&tp_driver)?;

    let mut battery_volt_adc_pin = AdcChannelDriver::new(&adc, gpio2, &adc_config)?;
    let adc_value: u32 = adc.read(&mut battery_volt_adc_pin)?.into();
    info!("battery voltage: {}", adc_value);

    let mut batt_v = 0;
    for _i in 0..16 {
        let adc_value: u32 = adc.read(&mut battery_volt_adc_pin)?.into();
        batt_v += adc_value; // ADC with correction
    }
    let batt_v = batt_v as f32 / 16.;
    // attenuation ratio (12 dB; 25%), mV --> V
    let batt_v = calc_adc_volt_in(batt_v, 12, 1395., 0.25) / 1000.;
    const RES1: f32 = 4100.;
    const RES2: f32 = 1000.;
    let battery_voltage = calc_volt_divider_in(RES1, RES2, batt_v);
    info!("battery voltage corrected: {}", battery_voltage);

    let mut light_intensity_adc_pin = AdcChannelDriver::new(&adc, gpio3, &adc_config)?;
    let adc_value: u32 = adc.read(&mut light_intensity_adc_pin)?.into();
    info!("light intensity: {}", adc_value);

    let mut light_intensity = 0;
    for _i in 0..16 {
        let adc_value: u32 = adc.read(&mut light_intensity_adc_pin)?.into();
        light_intensity += adc_value; // ADC with correction
    }
    // attenuation ratio (12 dB; 25%), mV --> V
    let light_intensity = light_intensity as f32 / 16.;
    info!("light intensity corrected: {}", light_intensity);
    let measure_time = cur_datetime(i2c)?;
    info!("cur time: {measure_time}");

    Ok(MeasurementsF32 {
        temperature,
        humidity,
        air_pressure,
        chip_temperature,
        light_intensity,
        battery_voltage,
        measure_time,
    })
}

fn publish_measurements<'m, 'i: 'm>(
    client: &mut EspMqttClient,
    measurements: &[MeasurementsF32],
) -> Result<()> {
    for m in measurements.iter() {
        let &MeasurementsF32 {
            temperature,
            humidity,
            air_pressure,
            chip_temperature,
            light_intensity,
            battery_voltage,
            measure_time,
        } = m;

        info!("publish measure: {m:?}...");
        publish_simple_measurements(
            client,
            &[
                create_measurement_f32(SensorType::Temperature, temperature, measure_time),
                create_measurement_f32(SensorType::Humidity, humidity, measure_time),
                create_measurement_f32(SensorType::Airpressure, air_pressure, measure_time),
                create_measurement_f32(SensorType::ChipTemperature, chip_temperature, measure_time),
                create_measurement_f32(SensorType::LightIntensity, light_intensity, measure_time),
                create_measurement_f32(SensorType::BatteryVoltage, battery_voltage, measure_time),
            ],
        )?;
        info!("...published");
    }

    /*
     * TODO
    if app_config.feature_co2_sensor_active {
        let co2_sensor = &mut co2_sensor.as_mut().unwrap();
        let co2_adc_val = adc.read(&mut adc_pin)?;
        read_publish_mq135_co2(client, co2_sensor, co2_adc_val, t, h, cur_datetime)?;
    }
    */

    Ok(())
}

/// voltage divider formula:
///   Vout = Vin * (R2 / (R1 + R2))
/// to solve for Vin:
///   Vin = Vout / (R2 / (R1 + R2))
///
/// PANIC:
/// Input parameter res2 should not be zero
/// otherwise division by zero occurs.
/// Input parameters res1 and res2
/// added together should not equal zero,
/// otherwise division by zero occurs.
fn calc_volt_divider_in(res1: f32, res2: f32, volt_out: f32) -> f32 {
    // Vin
    volt_out / (res2 / (res1 + res2))
}

fn calc_adc_volt_in(data_adc_val: f32, bitwidth: u32, volt_ref: f32, attenuation: f32) -> f32 {
    (volt_ref / attenuation as f32) * (data_adc_val / (2_u32.pow(bitwidth) - 1) as f32)
}

fn setup_bme280_temp_hum_airpr_sensor<'m, 'i: 'm>(
    i2c: &'m mut I2cDriver<'i>,
) -> Result<(BME280<&'m mut I2cDriver<'i>>, Delay)> {
    let mut bme280_sensor = BME280::new_primary(i2c);
    let mut delay = Delay::new(10);

    match bme280_sensor.init(&mut delay) {
        Err(e) => Err(anyhow!("bme280 sensor init failed for I2C!: error: {:?}", e).into()),
        Ok(()) => Ok((bme280_sensor, delay)),
    }
}

fn setup_co2_sensor<'d>(adc_value: u16) -> anyhow::Result<Mq135> {
    let mut co2_sensor = Mq135::new(20.0); // RL load resistance in kOhms

    sleep(std::time::Duration::from_secs(1));
    co2_sensor.calibrate_in_clean_air(adc_value)?;
    let (co2_ppm, adc_val) = co2_sensor.read_gas_ppm(GasType::CO2, adc_value)?;

    info!("CO2 Concentration: {} ppm; adc val: {}", co2_ppm, adc_val);
    Ok(co2_sensor)
}

fn read_publish_mq135_co2<'d>(
    client: &mut EspMqttClient,
    co2_sensor: &mut Mq135,
    adc_value: u16,
    t: f32,
    h: f32,
    measure_time: NaiveDateTime,
) -> Result<()> {
    let (co2_ppm, adc_val) = co2_sensor.read_gas_ppm(GasType::CO2, adc_value).unwrap();
    info!("CO2 Concentration: {} ppm; adc val: {}", co2_ppm, adc_val);

    publish_mq135_co2(client, co2_sensor, adc_value as u32, t, h, measure_time)
}

fn publish_mq135_co2(
    client: &mut EspMqttClient,
    co2_sensor: &Mq135,
    adc_value: u32,
    t: f32,
    h: f32,
    measure_time: NaiveDateTime,
) -> Result<()> {
    let co2_ppm = co2_sensor.get_ppm(adc_value);
    info!("CO2 Concentration: {} ppm; adc val: {}", co2_ppm, adc_value);
    let co2_ppm = co2_sensor.get_corrected_ppm(adc_value, t, h);
    info!(
        "corrected CO2 Concentration: {} ppm; adc val: {}",
        co2_ppm, adc_value
    );
    let co2_measure = api::Co2Measurement {
        co2_ppm: BigDecimal::from_f32(co2_ppm).expect("f32 could not be parsed to BigDecimal."),
        res0: BigDecimal::from_f32(co2_sensor.get_rzero(adc_value))
            .expect("f32 could not be parsed to BigDecimal."),
        adc_val: adc_value as i32,
        measure_time: measure_time.and_utc(),
    };
    let sensor_co2_measure = api::SensorSingleCo2Measure {
        sensor_reference: "bme280_1".into(),
        co2_measure,
    };
    if let Ok(sens_temps_str) = serde_json::to_string(&sensor_co2_measure) {
        client
            .publish(
                &TOPICS.co2,
                QoS::AtLeastOnce,
                false,
                &sens_temps_str.as_bytes(),
            )
            .map_err(|e| anyhow!("Could not send bme280 temperature. error: {e}"))?;
    }
    Ok(())
}

fn measure_chip_temperature(tp_driver: &TempSensorDriver) -> Result<f32> {
    // measure chip temperature
    let temp_val = tp_driver
        .get_celsius()
        .map_err(|e| anyhow!("Could not access chip temperature. error: {e}"))?;
    info!("chip temperature: {}", temp_val);

    Ok(temp_val)
}

fn measure_bme280_values(
    bme280_sensor: &mut BME280<&mut I2cDriver>,
    mut delay: Delay,
) -> Result<(f32, f32, f32)> {
    // measure multiple times, sort the results and choose
    // the mid value,
    // because the first measurements after the microcontroller
    // started or after deep sleep are most of the time incorrect
    // the measurement after it will be more accurate
    let _ = bme280_sensor.measure(&mut delay);

    let mut measurements = Vec::with_capacity(12);
    for _i in 0..12 {
        sleep(Duration::from_millis(20));
        match bme280_sensor.measure(&mut delay) {
            Ok(m) => measurements.push(m),
            Err(e) => {
                info!("bme280 measurement error: {:?}", e);
            }
        }
    }
    measurements.sort_by(|m1, m2| m1.temperature.total_cmp(&m2.temperature));
    let (s, _) = measurements.split_at(measurements.len() / 2);
    let mid = if let Some(mid) = s.last() {
        mid
    } else {
        return Err(anyhow!("Could not measure anything with bme280"));
    };
    let &Measurements::<I2cError> {
        temperature,
        humidity,
        pressure,
        ..
    } = mid;
    Ok((temperature, humidity, pressure))
}

fn publish_simple_measurements(
    client: &mut EspMqttClient,
    measurements: &[api::SensorTypedSimpleMeasurementF32],
) -> Result<MessageId> {
    let sens_temps = api::SensorTypedSimpleMeasurementsBorrowed {
        sensor_reference: "bme280_1",
        measurements,
    };

    let sens_temps_str = serde_json::to_string(&sens_temps)?;
    let msg_id = client
        .publish(
            &TOPICS.measurement_bundle,
            QoS::AtLeastOnce,
            false,
            &sens_temps_str.as_bytes(),
        )
        .map_err(|e| anyhow!("Could not send bme280 measurements. error: {e}"))?;
    Ok(msg_id)
}

fn create_measurement_f32(
    sensor_type: SensorType,
    measurement: f32,
    measure_time: NaiveDateTime,
) -> api::SensorTypedSimpleMeasurementF32 {
    let measure = api::SimpleMeasurementF32 {
        measurement,
        measure_time: measure_time.and_utc(),
    };
    api::SensorTypedSimpleMeasurementF32 {
        sensor_type,
        measure,
    }
}

fn publish_sensor_error_log_err(client: &mut EspMqttClient, error: anyhow::Error, error_time: NaiveDateTime) {
    if let Err(e) = publish_sensor_error(client, &TOPICS.error, error, error_time) {
        log::error!("Error while trying to publish sensor error: {}", e);
    }
}

fn publish_sensor_error(
    client: &mut EspMqttClient,
    topic: &'static str,
    error: anyhow::Error,
    error_time: NaiveDateTime,
) -> Result<()> {
    info!("sensor error: {}", error.root_cause());

    let sensor_error = api::SensorError {
        sensor_reference: "bme280_1".into(),
        error: api::Error {
            error_code: api::ErrorCode::PlaceHolder,
            error_text: error.root_cause().to_string(),
            error_time: error_time.and_utc(),
        },
    };

    let sensor_error_str = serde_json::to_string(&sensor_error)?;
    client
        .publish(topic, QoS::AtLeastOnce, false, &sensor_error_str.as_bytes())
        .map_err(|e| anyhow!("Could not send sensor error. error: {e}"))?;
    Ok(())
}
